package salon_habana;

import java.util.List;

public class NewBookingDialog extends javax.swing.JDialog {

        private List<BookingData> db;

        /**
         * Creates new form NewBookingDialog
         */
        public NewBookingDialog(java.awt.Frame parent, boolean modal, List<BookingData> db) {
                super(parent, modal);
                initComponents();
                this.db = db;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                NameLabel = new javax.swing.JLabel();
                NameTextField = new javax.swing.JTextField();
                PhoneLabel = new javax.swing.JLabel();
                PhoneTextField = new javax.swing.JTextField();
                DateSpinner = new javax.swing.JSpinner();
                DateLabel = new javax.swing.JLabel();
                TypeLabel = new javax.swing.JLabel();
                TypeComboBox = new javax.swing.JComboBox<>();
                AttendeesSpinner = new javax.swing.JSpinner();
                AttendeesLabel = new javax.swing.JLabel();
                FoodLabel = new javax.swing.JLabel();
                FoodComboBox = new javax.swing.JComboBox<>();
                RoomsCheckBox = new javax.swing.JCheckBox();
                Separator = new javax.swing.JSeparator();
                NDaysLabel = new javax.swing.JLabel();
                NDaysSpinner = new javax.swing.JSpinner();
                ConfirmButton = new javax.swing.JButton();
                CancelButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Nueva Reserva");
                setResizable(false);

                NameLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                NameLabel.setText("Nombre:");

                NameTextField.setToolTipText("Nombre de la persona que realiza la reserva");

                PhoneLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                PhoneLabel.setText("Teléfono:");

                PhoneTextField.setToolTipText("Teléfono de la persona que realiza la reserva");

                DateSpinner.setModel(new javax.swing.SpinnerDateModel());
                DateSpinner.setToolTipText("Fecha de la reserva");

                DateLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                DateLabel.setText("Fecha");

                TypeLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                TypeLabel.setText("Tipo:");

                TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Banquete", "Jornada", "Congreso" }));
                TypeComboBox.setToolTipText("Tipo de evento");
                TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                TypeComboBoxActionPerformed(evt);
                        }
                });

                AttendeesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
                AttendeesSpinner.setToolTipText("Número de asistentes");

                AttendeesLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                AttendeesLabel.setText("Asistentes:");

                FoodLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                FoodLabel.setText("Cocina:");

                FoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Bufé", "Carta", "Pedir cita con el Chef", "No precisa" }));
                FoodComboBox.setToolTipText("Tipo de comida solicitada");

                RoomsCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                RoomsCheckBox.setText("Reservar Habitaciones");
                RoomsCheckBox.setEnabled(false);

                NDaysLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
                NDaysLabel.setText("Nº de jornadas:");

                NDaysSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
                NDaysSpinner.setToolTipText("Jornadas del congreso");
                NDaysSpinner.setEnabled(false);

                ConfirmButton.setText("Confirmar");
                ConfirmButton.setToolTipText("Confirmar la reserva");
                ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ConfirmButtonActionPerformed(evt);
                        }
                });

                CancelButton.setText("Cancelar");
                CancelButton.setToolTipText("Cancelar la reserva");
                CancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CancelButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup().addComponent(ConfirmButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(39, 39, 39).addComponent(CancelButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                143,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(NameLabel)
                                                                                .addComponent(PhoneLabel)
                                                                                .addComponent(DateLabel)
                                                                                .addComponent(TypeLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                46,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(AttendeesLabel)
                                                                                .addComponent(FoodLabel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                54,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(NameTextField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                162,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                                .addComponent(PhoneTextField)
                                                                                                                .addComponent(DateSpinner,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                162,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(TypeComboBox,
                                                                                                                                0,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(FoodComboBox,
                                                                                                                                0,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(AttendeesSpinner,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                61,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(Separator,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                230,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(NDaysLabel)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(NDaysSpinner,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                59,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(RoomsCheckBox)).addContainerGap(65, Short.MAX_VALUE)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(22, 22, 22).addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(NameLabel).addComponent(NameTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(PhoneTextField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(PhoneLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(DateSpinner,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(DateLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(TypeComboBox,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(TypeLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(AttendeesSpinner,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(AttendeesLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(FoodLabel).addComponent(FoodComboBox,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(NDaysLabel).addComponent(NDaysSpinner,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18).addComponent(RoomsCheckBox).addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(ConfirmButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(CancelButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(70, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CancelButtonActionPerformed
                this.dispose();
        }// GEN-LAST:event_CancelButtonActionPerformed

        private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TypeComboBoxActionPerformed
                if (TypeComboBox.getSelectedItem().equals("Congreso")) {
                        NDaysSpinner.setEnabled(true);
                        RoomsCheckBox.setEnabled(true);
                } else {
                        NDaysSpinner.setEnabled(false);
                        NDaysSpinner.setValue(1);
                        RoomsCheckBox.setEnabled(false);
                        RoomsCheckBox.getModel().setSelected(false);
                }
        }// GEN-LAST:event_TypeComboBoxActionPerformed

        private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ConfirmButtonActionPerformed
                BookingData data = new BookingData();
                data.setName(NameTextField.getText());
                data.setPhone(PhoneTextField.getText());
                data.setDate(DateSpinner.getValue().toString());
                data.setType(TypeComboBox.getSelectedItem().toString());
                data.setAttendes((int) AttendeesSpinner.getValue());
                data.setFood(FoodComboBox.getSelectedItem().toString());
                data.setDays((int) NDaysSpinner.getValue());
                data.setRooms(RoomsCheckBox.getModel().isSelected());

                db.add(data);
                this.dispose();
        }// GEN-LAST:event_ConfirmButtonActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(NewBookingDialog.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(NewBookingDialog.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(NewBookingDialog.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(NewBookingDialog.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(() -> {
                        NewBookingDialog dialog = new NewBookingDialog(new javax.swing.JFrame(), true, null);
                        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                @Override
                                public void windowClosing(java.awt.event.WindowEvent e) {
                                        System.exit(0);
                                }
                        });
                        dialog.setVisible(true);
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel AttendeesLabel;
        private javax.swing.JSpinner AttendeesSpinner;
        private javax.swing.JButton CancelButton;
        private javax.swing.JButton ConfirmButton;
        private javax.swing.JLabel DateLabel;
        private javax.swing.JSpinner DateSpinner;
        private javax.swing.JComboBox<String> FoodComboBox;
        private javax.swing.JLabel FoodLabel;
        private javax.swing.JLabel NDaysLabel;
        private javax.swing.JSpinner NDaysSpinner;
        private javax.swing.JLabel NameLabel;
        private javax.swing.JTextField NameTextField;
        private javax.swing.JLabel PhoneLabel;
        private javax.swing.JTextField PhoneTextField;
        private javax.swing.JCheckBox RoomsCheckBox;
        private javax.swing.JSeparator Separator;
        private javax.swing.JComboBox<String> TypeComboBox;
        private javax.swing.JLabel TypeLabel;
        // End of variables declaration//GEN-END:variables
}
