version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/Formulario"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/Habana/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Caribe"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Primitiva"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/VisorImagen"
    schedule:
      interval: "weekly"